/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema;

import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.Timer;
import java.time.LocalDateTime;

/**
 *
 * @author paola
 */
public class AgenteReservas extends javax.swing.JFrame {

 

    /**
     * Creates new form AgenteReservas
     */
    public AgenteReservas() {
        initComponents();
        setLocationRelativeTo(null); // Centra la ventana
        fechaactual.setText(fecha());
        iniciarReloj();
  

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        reservasBtn = new javax.swing.JButton();
        listaReservasBtn = new javax.swing.JButton();
        listaVuelosBtn = new javax.swing.JButton();
        listaEsperaBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        tittle = new javax.swing.JLabel();
        imagen1 = new javax.swing.JLabel();
        imagen2 = new javax.swing.JLabel();
        imagen3 = new javax.swing.JLabel();
        imagen4 = new javax.swing.JLabel();
        frase1 = new javax.swing.JLabel();
        frase2 = new javax.swing.JLabel();
        fechaactual = new javax.swing.JLabel();
        horaactual = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(30, 134, 190));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reservasBtn.setBackground(new java.awt.Color(86, 180, 225));
        reservasBtn.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        reservasBtn.setText("Reservas");
        reservasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservasBtnActionPerformed(evt);
            }
        });
        jPanel1.add(reservasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 180, 50));

        listaReservasBtn.setBackground(new java.awt.Color(86, 180, 225));
        listaReservasBtn.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        listaReservasBtn.setText("Lista de Reservas");
        listaReservasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaReservasBtnActionPerformed(evt);
            }
        });
        jPanel1.add(listaReservasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 180, 50));

        listaVuelosBtn.setBackground(new java.awt.Color(86, 180, 225));
        listaVuelosBtn.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        listaVuelosBtn.setText("Lista de Vuelos");
        listaVuelosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaVuelosBtnActionPerformed(evt);
            }
        });
        jPanel1.add(listaVuelosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 282, 183, 50));

        listaEsperaBtn.setBackground(new java.awt.Color(86, 180, 225));
        listaEsperaBtn.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        listaEsperaBtn.setText("Lista de Espera");
        listaEsperaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaEsperaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(listaEsperaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 183, 50));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 210, 10));

        tittle.setFont(new java.awt.Font("Lucida Bright", 1, 28)); // NOI18N
        tittle.setText("SKYBOOKER");
        tittle.setToolTipText("");
        jPanel1.add(tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, -1));

        imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/home.png"))); // NOI18N
        jPanel1.add(imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/usuarios.png"))); // NOI18N
        jPanel1.add(imagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        imagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/lista.png"))); // NOI18N
        jPanel1.add(imagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        imagen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/calendario.png"))); // NOI18N
        imagen4.setToolTipText("");
        jPanel1.add(imagen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        frase1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        frase1.setText("La felicidad comienza con un: ");
        jPanel1.add(frase1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 230, -1));

        frase2.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        frase2.setText("¡Bienvenido a bordo!");
        jPanel1.add(frase2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        fechaactual.setBackground(new java.awt.Color(255, 255, 255));
        fechaactual.setFont(new java.awt.Font("Lucida Bright", 1, 20)); // NOI18N
        fechaactual.setForeground(new java.awt.Color(255, 255, 255));
        fechaactual.setText("DD/MM/YYYY");
        jPanel1.add(fechaactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 150, -1));

        horaactual.setBackground(new java.awt.Color(255, 255, 255));
        horaactual.setFont(new java.awt.Font("Lucida Bright", 1, 20)); // NOI18N
        horaactual.setForeground(new java.awt.Color(255, 255, 255));
        horaactual.setText("HH:mm:ss");
        jPanel1.add(horaactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 550));

        contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        background.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 840, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reservasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservasBtnActionPerformed
        // TODO add your handling code here:

        AReservas p1 = new AReservas();
        ShowPanel(p1.getFondo());


    }//GEN-LAST:event_reservasBtnActionPerformed

    private void listaReservasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaReservasBtnActionPerformed
        // TODO add your handling code here:

        AListaReservas p2 = new AListaReservas();
        ShowPanel(p2.getFondo());

    }//GEN-LAST:event_listaReservasBtnActionPerformed

    private void listaVuelosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaVuelosBtnActionPerformed
        // TODO add your handling code here:
        AListaVuelos p3 = new AListaVuelos();
        ShowPanel(p3.getFondo());
    }//GEN-LAST:event_listaVuelosBtnActionPerformed

    private void listaEsperaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaEsperaBtnActionPerformed
        // TODO add your handling code here:
        AListaEspera p4 = new AListaEspera();
        ShowPanel(p4.getFondo());

    }//GEN-LAST:event_listaEsperaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    private void ShowPanel(JPanel p) {

        p.setSize(820, 530);//[820, 530]
        p.setLocation(0, 0);

        contenido.removeAll();
        contenido.add(p, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();

    }

    public void iniciarReloj() {
        Timer timer = new Timer(1000, e -> {
            Date hora = new Date();
            SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
            horaactual.setText(formatoHora.format(hora));
        });
        timer.start();
    }

    public static String fecha() {

        Date fecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        return formato.format(fecha);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgenteReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgenteReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgenteReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgenteReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AgenteReservas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel fechaactual;
    private javax.swing.JLabel frase1;
    private javax.swing.JLabel frase2;
    private javax.swing.JLabel horaactual;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel imagen2;
    private javax.swing.JLabel imagen3;
    private javax.swing.JLabel imagen4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton listaEsperaBtn;
    private javax.swing.JButton listaReservasBtn;
    private javax.swing.JButton listaVuelosBtn;
    private javax.swing.JButton reservasBtn;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
