/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema;

import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paola
 */
public class AListaReservas extends javax.swing.JFrame {

    private final GestorVuelos gestorVuelos = GestorVuelos.getInstancia();
    private GestorReservas gestorReservas = GestorReservas.getInstancia();

    /**
     * Creates new form AListaReservas
     */
    public AListaReservas() {
        initComponents();
        llenadoComboVuelo();
        llenadoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtablaReservas = new javax.swing.JTable();
        eliminarBtn = new javax.swing.JButton();
        actualizarBtn = new javax.swing.JButton();
        correoActual = new javax.swing.JLabel();
        correoActualTxt = new javax.swing.JTextField();
        claseActual = new javax.swing.JLabel();
        claseActualComboBox = new javax.swing.JComboBox<>();
        idaActual = new javax.swing.JLabel();
        vueltaActual = new javax.swing.JLabel();
        idaDateChooser = new com.toedter.calendar.JDateChooser();
        vueltaDateChooser = new com.toedter.calendar.JDateChooser();
        vuelos = new javax.swing.JLabel();
        vuelosActualesComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(30, 100, 250));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Reservas hechas:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(581, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 63));

        JtablaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JtablaReservas);

        fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 690, 270));

        eliminarBtn.setBackground(new java.awt.Color(255, 0, 0));
        eliminarBtn.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        eliminarBtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarBtn.setText("ELIMINAR");
        fondo.add(eliminarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 110, 40));

        actualizarBtn.setBackground(new java.awt.Color(0, 0, 102));
        actualizarBtn.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        actualizarBtn.setForeground(new java.awt.Color(255, 255, 255));
        actualizarBtn.setText("ACTUALIZAR");
        fondo.add(actualizarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, -1, 40));

        correoActual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        correoActual.setText("Correo Electrónico:");
        fondo.add(correoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, -1));

        correoActualTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fondo.add(correoActualTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 200, 36));

        claseActual.setBackground(new java.awt.Color(255, 255, 255));
        claseActual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        claseActual.setText("Clase:");
        fondo.add(claseActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        claseActualComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta", "Económica", " " }));
        fondo.add(claseActualComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 200, 36));

        idaActual.setBackground(new java.awt.Color(255, 255, 255));
        idaActual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idaActual.setText("Ida:");
        fondo.add(idaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        vueltaActual.setBackground(new java.awt.Color(255, 255, 255));
        vueltaActual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vueltaActual.setText("Vuelta:");
        fondo.add(vueltaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));
        fondo.add(idaDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 200, 36));
        fondo.add(vueltaDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 200, 36));

        vuelos.setBackground(new java.awt.Color(255, 255, 255));
        vuelos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vuelos.setText("Vuelos Disponibles:");
        fondo.add(vuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        vuelosActualesComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vuelosActualesComboBox.setName("cmbVuelo"); // NOI18N
        fondo.add(vuelosActualesComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 200, 36));
        vuelosActualesComboBox.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public JPanel getFondo() {
        return fondo;
    }

    public void llenadoComboVuelo() {
        List<Vuelo> listaVuelo = gestorVuelos.getVuelos();

        // LLENA EL COMBO CON LA LISTA DE VUELOS
        listaVuelo.forEach(vuelo -> vuelosActualesComboBox.addItem(vuelo.getDestino()));
    }

    public void llenadoTable() {
        // Definir las columnas que se mostrarán en la tabla
        String[] columnas = {"ID Reserva", "Nombre", "Correo", "Vuelo", "Asiento", "Clase"};

        // Crear el modelo de tabla con las columnas definidas
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

        // Obtener la lista de reservas
        List<Reserva> reservas = gestorReservas.getReservas();

        // Llenar la tabla con los datos de cada reserva
        for (Reserva reserva : reservas) {
            String id = reserva.getIdReserva();
            String nombre = reserva.getPasajero().getNombre() + " " + reserva.getPasajero().getApellido();
            String correo = reserva.getPasajero().getEmail();
            String vuelo = reserva.getVuelo().getDestino(); // O podés usar un método más descriptivo
            String asiento = reserva.getAsiento();
            String clase = reserva.getClaseViaje().toString();
            

            // Agregar la fila al modelo
            Object[] fila = {id, nombre, correo, vuelo, asiento, clase};
            modelo.addRow(fila);
        }

        // Establecer el modelo en la tabla
        JtablaReservas.setModel(modelo);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AListaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AListaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AListaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AListaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AListaReservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtablaReservas;
    private javax.swing.JButton actualizarBtn;
    private javax.swing.JLabel claseActual;
    private javax.swing.JComboBox<String> claseActualComboBox;
    private javax.swing.JLabel correoActual;
    private javax.swing.JTextField correoActualTxt;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel idaActual;
    private com.toedter.calendar.JDateChooser idaDateChooser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel vuelos;
    private javax.swing.JComboBox<String> vuelosActualesComboBox;
    private javax.swing.JLabel vueltaActual;
    private com.toedter.calendar.JDateChooser vueltaDateChooser;
    // End of variables declaration//GEN-END:variables
}
