/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author paola
 */
public class AReservas extends javax.swing.JFrame {

    /**
     * Creates new form AReservas
     */
    public AReservas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        reservarBtn = new javax.swing.JButton();
        nombresTxt = new javax.swing.JTextField();
        nombres = new javax.swing.JLabel();
        apellidosTxt = new javax.swing.JTextField();
        idPasaporteTxt = new javax.swing.JTextField();
        correoTxt = new javax.swing.JTextField();
        apellidos = new javax.swing.JLabel();
        idPasaporte = new javax.swing.JLabel();
        correo = new javax.swing.JLabel();
        fechaNacimiento = new javax.swing.JLabel();
        visa = new javax.swing.JLabel();
        siCheckbox = new java.awt.Checkbox();
        noCheckbox = new java.awt.Checkbox();
        nacionalidad = new javax.swing.JLabel();
        nacionalidadComboBox = new javax.swing.JComboBox<>();
        fechaNacimientoDateChooser = new com.toedter.calendar.JDateChooser();
        paisOrigen = new javax.swing.JLabel();
        paisDestino = new javax.swing.JLabel();
        paisesOrigenComboBox = new javax.swing.JComboBox<>();
        paisesDestinoComboBox = new javax.swing.JComboBox<>();
        ida = new javax.swing.JLabel();
        idaDateChooser = new com.toedter.calendar.JDateChooser();
        vueltaDateChooser = new com.toedter.calendar.JDateChooser();
        VuelosComboBox = new javax.swing.JComboBox<>();
        clasesComboBox = new javax.swing.JComboBox<>();
        clases = new javax.swing.JLabel();
        vuelta = new javax.swing.JLabel();
        vuelos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setPreferredSize(new java.awt.Dimension(840, 540));

        jPanel1.setBackground(new java.awt.Color(30, 100, 250));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese los siguientes datos del pasajero:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        reservarBtn.setBackground(new java.awt.Color(51, 153, 0));
        reservarBtn.setForeground(new java.awt.Color(255, 255, 255));
        reservarBtn.setText("RESERVAR");
        reservarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarBtnActionPerformed(evt);
            }
        });

        nombresTxt.setBackground(new java.awt.Color(255, 255, 255));
        nombresTxt.setForeground(new java.awt.Color(0, 0, 0));
        nombresTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nombres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombres.setForeground(new java.awt.Color(0, 0, 0));
        nombres.setText("Nombres:");

        apellidosTxt.setBackground(new java.awt.Color(255, 255, 255));
        apellidosTxt.setForeground(new java.awt.Color(0, 0, 0));
        apellidosTxt.setToolTipText("");
        apellidosTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        idPasaporteTxt.setBackground(new java.awt.Color(255, 255, 255));
        idPasaporteTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        idPasaporteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPasaporteTxtActionPerformed(evt);
            }
        });

        correoTxt.setBackground(new java.awt.Color(255, 255, 255));
        correoTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        apellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        apellidos.setForeground(new java.awt.Color(0, 0, 0));
        apellidos.setText("Apellidos:");

        idPasaporte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idPasaporte.setForeground(new java.awt.Color(0, 0, 0));
        idPasaporte.setText("ID del Pasaporte:");

        correo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        correo.setForeground(new java.awt.Color(0, 0, 0));
        correo.setText("Correo Electrónico:");

        fechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fechaNacimiento.setForeground(new java.awt.Color(0, 0, 0));
        fechaNacimiento.setText("Fecha de nacimiento:");

        visa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        visa.setForeground(new java.awt.Color(0, 0, 0));
        visa.setText("¿Tiene Visa?");

        siCheckbox.setLabel("si");

        noCheckbox.setLabel("no");

        nacionalidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nacionalidad.setForeground(new java.awt.Color(0, 0, 0));
        nacionalidad.setText("Nacionalidad:");

        nacionalidadComboBox.setBackground(new java.awt.Color(255, 255, 255));
        nacionalidadComboBox.setForeground(new java.awt.Color(0, 0, 0));
        nacionalidadComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "argentino/a", "boliviano/a", "brasileño/a", "chileno/a", "colombiano/a", "costarricense", "cubano/a", "ecuatoriano/a", "salvadoreño/a", "guatemalteco/a", "hondureño/a", "mexicano/a", "nicaragüense", "panameño/a", "paraguayo/a", "peruano/a", "dominicano/a", "uruguayo/a", "venezolano/a" }));
        nacionalidadComboBox.setBorder(null);

        fechaNacimientoDateChooser.setBackground(new java.awt.Color(255, 255, 255));
        fechaNacimientoDateChooser.setForeground(new java.awt.Color(0, 0, 0));

        paisOrigen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        paisOrigen.setForeground(new java.awt.Color(0, 0, 0));
        paisOrigen.setText("País de origen:");

        paisDestino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        paisDestino.setForeground(new java.awt.Color(0, 0, 0));
        paisDestino.setText("País de destino:");

        paisesOrigenComboBox.setBackground(new java.awt.Color(255, 255, 255));
        paisesOrigenComboBox.setForeground(new java.awt.Color(0, 0, 0));
        paisesOrigenComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Bolivia", "Brasil", "Chile", "Colombia", "Costa Rica", "Cuba", "Ecuador", "El Salvador", "Guatemala", "Honduras", "México", "Nicaragua", "Panamá", "Paraguay", "Perú", "República Dominicana\t", "Uruguay\t", "Venezuela" }));

        paisesDestinoComboBox.setBackground(new java.awt.Color(255, 255, 255));
        paisesDestinoComboBox.setForeground(new java.awt.Color(0, 0, 0));
        paisesDestinoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Bolivia", "Brasil", "Chile", "Colombia", "Costa Rica", "Cuba", "Ecuador", "El Salvador", "Guatemala", "Honduras", "México", "Nicaragua", "Panamá", "Paraguay", "Perú", "República Dominicana\t", "Uruguay\t", "Venezuela" }));

        ida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ida.setForeground(new java.awt.Color(0, 0, 0));
        ida.setText("Ida:");

        idaDateChooser.setBackground(new java.awt.Color(255, 255, 255));
        idaDateChooser.setForeground(new java.awt.Color(0, 0, 0));

        vueltaDateChooser.setBackground(new java.awt.Color(255, 255, 255));
        vueltaDateChooser.setForeground(new java.awt.Color(0, 0, 0));

        VuelosComboBox.setBackground(new java.awt.Color(255, 255, 255));
        VuelosComboBox.setForeground(new java.awt.Color(0, 0, 0));
        VuelosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        clasesComboBox.setBackground(new java.awt.Color(255, 255, 255));
        clasesComboBox.setForeground(new java.awt.Color(0, 0, 0));
        clasesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta", "Económica" }));

        clases.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clases.setForeground(new java.awt.Color(0, 0, 0));
        clases.setText("Clase:");

        vuelta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vuelta.setForeground(new java.awt.Color(0, 0, 0));
        vuelta.setText("Vuelta:");

        vuelos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vuelos.setForeground(new java.awt.Color(0, 0, 0));
        vuelos.setText("Vuelo:");

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idPasaporteTxt)
                                .addComponent(idPasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nombresTxt)
                                .addComponent(visa, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ida, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(fondoLayout.createSequentialGroup()
                                    .addComponent(siCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(noCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(clasesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(idaDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apellidosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(correoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(paisOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vuelta, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(paisesOrigenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(42, 42, 42)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paisDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(fondoLayout.createSequentialGroup()
                                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nacionalidadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fechaNacimientoDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 25, Short.MAX_VALUE)))
                                .addGap(12, 12, 12))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(paisesDestinoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reservarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(vueltaDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(VuelosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombres)
                            .addComponent(apellidos))
                        .addGap(18, 18, 18)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombresTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(fechaNacimiento)
                        .addGap(18, 18, 18)
                        .addComponent(fechaNacimientoDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paisOrigen, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(visa))
                                .addGap(18, 18, 18)
                                .addComponent(paisesOrigenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(idPasaporte)
                                .addGap(18, 18, 18)
                                .addComponent(idPasaporteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(siCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)))
                        .addGap(52, 52, 52))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nacionalidad)
                            .addComponent(correo))
                        .addGap(18, 18, 18)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nacionalidadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(correoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(fondoLayout.createSequentialGroup()
                                    .addComponent(paisDestino)
                                    .addGap(18, 18, 18)
                                    .addComponent(paisesDestinoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22)
                                    .addComponent(vuelos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(VuelosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(fondoLayout.createSequentialGroup()
                                    .addComponent(vuelta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(vueltaDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(ida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idaDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)))
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(clases)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clasesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(reservarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idPasaporteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPasaporteTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPasaporteTxtActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    
    private void reservarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public JPanel getFondo() {
        return fondo;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AReservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> VuelosComboBox;
    private javax.swing.JLabel apellidos;
    private javax.swing.JTextField apellidosTxt;
    private javax.swing.JLabel clases;
    private javax.swing.JComboBox<String> clasesComboBox;
    private javax.swing.JLabel correo;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JLabel fechaNacimiento;
    private com.toedter.calendar.JDateChooser fechaNacimientoDateChooser;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel idPasaporte;
    private javax.swing.JTextField idPasaporteTxt;
    private javax.swing.JLabel ida;
    private com.toedter.calendar.JDateChooser idaDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nacionalidad;
    private javax.swing.JComboBox<String> nacionalidadComboBox;
    private java.awt.Checkbox noCheckbox;
    private javax.swing.JLabel nombres;
    private javax.swing.JTextField nombresTxt;
    private javax.swing.JLabel paisDestino;
    private javax.swing.JLabel paisOrigen;
    private javax.swing.JComboBox<String> paisesDestinoComboBox;
    private javax.swing.JComboBox<String> paisesOrigenComboBox;
    private javax.swing.JButton reservarBtn;
    private java.awt.Checkbox siCheckbox;
    private javax.swing.JLabel visa;
    private javax.swing.JLabel vuelos;
    private javax.swing.JLabel vuelta;
    private com.toedter.calendar.JDateChooser vueltaDateChooser;
    // End of variables declaration//GEN-END:variables
}
